[package]
name = "tectonic_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "tectonic_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.28.0"
tectonic = "0.12.0"
